export const GET_TOURS = "GET_TOURS";
export const GET_TOURS_SUCCESS = "GET_TOURS_SUCCESS";
export const GET_TOURS_FAIL = "GET_TOURS_FAIL";

export const GET_TOUR_DETAILS = "GET_TOUR_DETAILS";
export const GET_TOUR_DETAILS_SUCCESS = "GET_TOUR_DETAILS_SUCCESS";
export const GET_TOUR_DETAILS_FAIL = "GET_TOUR_DETAILS_FAIL";
